'use strict';
let data,selected='2026-10-11',map,layer,markers={},showAllMap=false,interactive=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const place=id=>data.places.find(p=>p.id===id);
const navUrl=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.id==='dymon'?p.address+' '+p.name:p.coordinates?p.coordinates.join(','):p.address+' '+p.name);
const visit=p=>data.days.flatMap(d=>d.events.filter(e=>e.place===p.id).map(e=>`10月${d.day}日 ${e.time}${e.end?'—'+e.end:''}`)).join('；');
function activePlaces(all=false){const ids=new Set(data.days.find(d=>d.date===selected).events.map(e=>e.place));return data.places.filter(p=>all||ids.has(p.id))}
let toastTimer;
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').style.display='block';toastTimer=setTimeout(()=>$('#toast').style.display='none',5000)}
function selectDate(date,updateHash=true){selected=date;showAllMap=false;$('#all-map').textContent='显示全部地点';renderDay();renderCards();renderMap();if(updateHash)history.replaceState(null,'','#day='+date)}
function renderDay(){const d=data.days.find(d=>d.date===selected);$('#dates').innerHTML=data.days.map(x=>`<button class="date" aria-pressed="${x.date===selected}" data-date="${x.date}" aria-label="10月${x.day}日 ${esc(x.weekday)} ${esc(x.theme)}"><strong>${x.day}</strong><span>${esc(x.weekday)}</span></button>`).join('');$('#dates').querySelectorAll('button').forEach(b=>b.onclick=()=>selectDate(b.dataset.date));$('#day-header').innerHTML=`<h3>${esc(d.theme)}</h3><p>10月${d.day}日 ${esc(d.weekday)} · ${esc(d.region)}</p>`;$('#timeline').innerHTML=d.events.map(e=>`<li><div class="time">${esc(e.time)}${e.end?'<br>— '+esc(e.end):''}</div><div class="event"><h4>${esc(e.title)}</h4>${e.note?`<p>${esc(e.note)}</p>`:''}${e.place?`<button data-place="${e.place}">地点介绍与参访要求</button>`:''}</div></li>`).join('');$('#timeline').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.place));$('#task').textContent=d.task;$('#transport').textContent=d.transport;$('#notice').textContent=d.notice}
function renderCards(){const ps=activePlaces($('#place-filter').value==='all');$('#cards').innerHTML=ps.map(p=>`<article class="card">${p.image?`<div class="photo"><img src="${p.image}" alt="${esc(p.photo.caption)}" loading="lazy" width="800" height="500"></div>`:''}<div class="card-body"><p class="category">${esc(p.category)}</p><h3>${esc(p.name)}</h3><p class="english">${esc(p.en)}</p><p class="one-liner">${esc(p.topic)}</p><p class="visit">${esc(visit(p))}</p>${p.address?`<p class="address">${esc(p.address)}</p>`:''}<div class="card-actions"><button data-detail="${p.id}">阅读详情</button>${p.coordinates?`<button data-map="${p.id}">地点位置</button><a href="${navUrl(p)}" target="_blank" rel="noopener">联网导航</a>`:''}</div></div></article>`).join('');$('#cards').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));$('#cards').querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>focusMap(b.dataset.map))}
function initMap(){if(map)return true;if(!window.L)return false;map=L.map('map',{scrollWheelZoom:false}).setView([22.33,114.12],11);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);tiles.on('tileerror',()=>{if(interactive){showStaticMap();$('#map-status').textContent='互动底图未能加载，已显示参考地图。'}});layer=L.layerGroup().addTo(map);return true}
function showStaticMap(){interactive=false;$('#map').hidden=true;$('#offline-map').hidden=false;$('#toggle-map').textContent=navigator.onLine?'互动地图（联网）':'互动地图需联网';if(data)renderMap()}
function showInteractiveMap(){if(!navigator.onLine){toast('互动地图需联网；参考地图可离线查阅。');return}interactive=true;$('#map').hidden=false;$('#offline-map').hidden=true;$('#toggle-map').textContent='查看参考地图';if(!initMap()){showStaticMap();toast('请使用参考地图查看地点位置。');return}map.invalidateSize();renderMap()}
function renderMap(){const day=data.days.find(d=>d.date===selected),reference=showAllMap?data.overviewMap:day.map,ps=activePlaces(showAllMap).filter(p=>p.coordinates);$('#map-caption').textContent=(showAllMap?'区域概览':'10月'+day.day+'日地点')+' · 地图用于辨认楼宇和园区位置，图中编号不表示行车路线。';$('#static-map').src=reference.image;$('#static-map').alt=(showAllMap?'香港参访区域概览':'10月'+day.day+'日参访地点参考地图');$('#static-map-legend').textContent=reference.legend.map(p=>`${p.number}. ${p.name}`).join('；');$('#map-status').textContent=interactive?'互动地图标记为楼宇或校园参考点，入场按现场指引执行。':'参考地图可离线查阅；实时导航需联网。';$('#map-list').innerHTML=ps.map(p=>`<button data-focus="${p.id}">${esc(p.name)}</button>`).join('');$('#map-list').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.focus));if(!map||!interactive)return;layer.clearLayers();markers={};ps.forEach((p,i)=>{const type=p.category==='金融'?'finance':p.category==='治理'?'governance':'';const icon=L.divIcon({className:'map-pin '+type,html:String(i+1),iconSize:[30,30],iconAnchor:[15,15]});const m=L.marker(p.coordinates,{icon,title:p.name,alt:p.name}).addTo(layer);const box=document.createElement('div');box.innerHTML=`<strong>${esc(p.name)}</strong><br>${esc(p.address)}<br><a target="_blank" rel="noopener" href="${navUrl(p)}">联网导航</a><br><button>阅读地点详情</button>`;box.querySelector('button').onclick=()=>openDetail(p.id);m.bindPopup(box);markers[p.id]=m});if(ps.length)map.fitBounds(L.latLngBounds(ps.map(p=>p.coordinates)).pad(.3),{maxZoom:16})}
function focusMap(id){const p=place(id);if(!p?.coordinates)return;const day=data.days.find(d=>d.events.some(e=>e.place===id));if(!activePlaces(showAllMap).some(p=>p.id===id)&&day)selectDate(day.date);$('#map-section').scrollIntoView({behavior:'smooth'});if(interactive){renderMap();map.setView(p.coordinates,16);markers[id]?.openPopup()}else toast(p.name+'：请查看参考地图及地点说明。')}
function photoCredit(p){return `<p class="credit">${esc(p.photo.caption)}<br>照片：${esc(p.photo.author)}／<a href="${esc(p.photo.source)}" target="_blank" rel="noopener">Wikimedia Commons</a>／<a href="${esc(p.photo.licenseUrl)}" target="_blank" rel="noopener">${esc(p.photo.license)}</a>。照片为往年实景，已作尺寸调整及显示裁切。</p>`}
function openDetail(id,hash=true){const p=place(id);if(!p)return;$('#detail-body').innerHTML=`${p.image?`<img class="detail-photo" src="${p.image}" alt="${esc(p.photo.caption)}">`:''}<div class="detail-content"><p class="eyebrow">${esc(p.category)}</p><h2>${esc(p.name)}</h2><p class="english">${esc(p.en)}</p><p class="visit">${esc(visit(p))}</p>${p.address?`<p><strong>地址：</strong>${esc(p.address)}</p>`:''}<h3>地点介绍</h3><p>${esc(p.intro)}</p>${p.focus?`<h3>参访重点</h3>${p.focus.map(f=>`<p><strong>${esc(f.title)}：</strong>${esc(f.text)}</p>`).join('')}`:''}<h3>${esc(p.topic)}</h3><ul>${p.questions.map(q=>'<li>'+esc(q)+'</li>').join('')}</ul><h3>参访要求</h3><p>${esc(p.entry)}</p>${p.coordinates?`<p class="credit">${esc(p.coordinateNote)}</p><a class="button" href="${navUrl(p)}" target="_blank" rel="noopener">联网导航</a><button class="button secondary" id="detail-map">查看地点地图</button>`:''}<button class="button secondary" id="share-place">复制地点链接</button>${p.photo?photoCredit(p):''}</div>`;if(!$('#detail').open)$('#detail').showModal();document.body.classList.add('modal-open');$('#detail-map')?.addEventListener('click',()=>{closeDetail();focusMap(id)});$('#share-place').onclick=async()=>{const url=location.href.split('#')[0]+'#place='+id;try{await navigator.clipboard.writeText(url);toast('地点链接已复制')}catch{toast('可从地址栏复制当前地点链接')}};if(hash)history.replaceState(null,'','#place='+id)}
function closeDetail(){if($('#detail').open)$('#detail').close();document.body.classList.remove('modal-open');history.replaceState(null,'','#day='+selected)}
async function start(){try{const response=await fetch('data.json');if(!response.ok)throw new Error('行程读取失败');data=await response.json();const hash=new URLSearchParams(location.hash.slice(1)),initial=hash.get('day');if(data.days.some(d=>d.date===initial))selected=initial;else{const now=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong'}).format(new Date());if(data.days.some(d=>d.date===now))selected=now}$('#overview').innerHTML=data.overview.map(t=>'<p>'+esc(t)+'</p>').join('');$('#goals').innerHTML=data.goals.map(g=>`<div><h3>${esc(g.title)}</h3><p>${esc(g.text)}</p></div>`).join('');$('#notices').innerHTML=data.notices.map((n,i)=>`<details${i===0?' open':''}><summary>${esc(n.title)}</summary><p>${esc(n.text)}</p></details>`).join('');const h=data.heroPhoto;$('#photo-credits').innerHTML=`<div class="photo-credit"><strong>香港城市景观</strong><br>${esc(h.author)}／<a href="${h.source_page_url}" target="_blank" rel="noopener">Wikimedia Commons</a>／<a href="${h.license_url}" target="_blank" rel="noopener">${esc(h.license)}</a></div>`+data.places.filter(p=>p.photo).map(p=>`<div class="photo-credit"><strong>${esc(p.name)}</strong>${photoCredit(p)}</div>`).join('');renderDay();renderCards();renderMap();$('#place-filter').onchange=renderCards;$('#all-map').onclick=()=>{showAllMap=!showAllMap;$('#all-map').textContent=showAllMap?'显示当日地点':'显示全部地点';renderMap()};$('#toggle-map').onclick=()=>interactive?showStaticMap():showInteractiveMap();$('#today').onclick=()=>{const t=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong'}).format(new Date());if(data.days.some(d=>d.date===t))selectDate(t);else{selectDate('2026-10-11');toast('今天不在实践日期内，已显示10月11日。')}};$('.close').onclick=closeDetail;$('#detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail()});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))closeDetail()});if(hash.has('place')){const p=place(hash.get('place'));const day=data.days.find(d=>d.events.some(e=>e.place===p?.id));if(day)selectDate(day.date,false);openDetail(hash.get('place'),false)}updateConnectivity()}catch(e){$('#day-header').innerHTML='<p>行程未能载入，请联网重新打开，或查阅已保存的 PDF 路书。</p>';console.error(e)}}
function updateConnectivity(){if(!navigator.onLine&&interactive)showStaticMap();$('#toggle-map').disabled=!navigator.onLine;if(!interactive)$('#toggle-map').textContent=navigator.onLine?'互动地图（联网）':'互动地图需联网'}
window.addEventListener('offline',updateConnectivity);window.addEventListener('online',updateConnectivity);
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&/^https?:/.test(a.href)&&new URL(a.href).origin!==location.origin&&!navigator.onLine){e.preventDefault();toast('该链接需联网打开。')}});
window.addEventListener('hashchange',()=>{if(!data)return;const h=new URLSearchParams(location.hash.slice(1));if(h.has('place'))openDetail(h.get('place'),false);if(data.days.some(d=>d.date===h.get('day')))selectDate(h.get('day'),false)});
start();
