'use strict';
let data,selected='2026-10-11',map,layer,markers={},showAllMap=false;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const place=id=>data.places.find(p=>p.id===id);
const navUrl=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.id==='dymon'?p.address+' '+p.name:p.coordinates?p.coordinates.join(','):p.address+' '+p.name);
const visit=p=>data.days.flatMap(d=>d.events.filter(e=>e.place===p.id).map(e=>`10月${d.day}日 ${e.time}${e.end?'–'+e.end:''}`)).join(' · ');
function activePlaces(all=false){const ids=new Set(data.days.find(d=>d.date===selected).events.map(e=>e.place));return data.places.filter(p=>all||ids.has(p.id))}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
function selectDate(date,updateHash=true){selected=date;showAllMap=false;renderDay();renderCards();renderMap();if(updateHash)history.replaceState(null,'','#day='+date)}
function renderDay(){const d=data.days.find(d=>d.date===selected);$('#dates').innerHTML=data.days.map(x=>`<button class="date" aria-pressed="${x.date===selected}" data-date="${x.date}" aria-label="10月${x.day}日 ${x.weekday} ${esc(x.theme)}"><strong>${x.day}</strong><span>${x.weekday}</span></button>`).join('');$('#dates').querySelectorAll('button').forEach(b=>b.onclick=()=>selectDate(b.dataset.date));$('#day-header').innerHTML=`<h3>${esc(d.theme)}</h3><p>10月${d.day}日 ${d.weekday} · ${esc(d.region)}</p>`;$('#timeline').innerHTML=d.events.map(e=>`<li><div class="time">${esc(e.time)}${e.end?'<br>'+esc(e.end):''}</div><div class="event"><h4>${esc(e.title)}</h4>${e.status!=='V4已列明'?`<span class="status">${esc(e.status)}</span>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}${e.place?`<button data-place="${e.place}">地点与访问提示</button>`:''}</div></li>`).join('');$('#timeline').querySelectorAll('button').forEach(b=>b.onclick=()=>openDetail(b.dataset.place));$('#task').textContent=d.task;$('#transport').textContent=d.transport;$('#notice').textContent=d.notice}
function renderCards(){const ps=activePlaces($('#place-filter').value==='all');$('#cards').innerHTML=ps.map(p=>`<article class="card"><div class="photo">${p.image?`<img src="${p.image}" alt="${esc(p.photo.caption)}" loading="lazy" width="800" height="500">`:'<div class="no-photo"><strong>到访地点待确认</strong><span>暂不展示未经核实的场地照片</span></div>'}</div><div class="card-body"><p class="category">${esc(p.category)}</p><h3>${esc(p.name)}</h3><p class="english">${esc(p.en)}</p><p class="one-liner">${esc(p.topic)}</p><p class="visit">${esc(visit(p))}</p><p class="address">${esc(p.address)}</p><div class="card-actions"><button data-detail="${p.id}">阅读详情</button>${p.coordinates?`<button data-map="${p.id}">地图定位</button><a href="${navUrl(p)}" target="_blank" rel="noopener">导航</a>`:''}</div></div></article>`).join('');$('#cards').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));$('#cards').querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>focusMap(b.dataset.map))}
function initMap(){if(!window.L){$('#map').innerHTML='<p>互动地图暂时不可用，请使用地点详情中的导航链接。</p>';return}map=L.map('map',{scrollWheelZoom:false}).setView([22.33,114.12],11);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);tiles.on('tileerror',()=>$('#map-status').textContent='部分底图未能加载；地点标记和外部导航仍可使用。');tiles.on('load',()=>{});layer=L.layerGroup().addTo(map)}
function renderMap(){const ps=activePlaces(showAllMap).filter(p=>p.coordinates);$('#map-caption').textContent=(showAllMap?'全部地点':'10月'+data.days.find(d=>d.date===selected).day+'日地点')+' · 标记为楼宇或校园参考点，不代表预约入口。不绘制推测行车路线。';$('#map-status').innerHTML='绿色：科研、高校、交通等 · 棕色：治理 · 蓝色：金融。 <a target="_blank" href="'+data.days.find(d=>d.date===selected).map.image+'">查看当日静态参考地图</a>';$('#map-list').innerHTML=ps.map((p,i)=>`<button data-focus="${p.id}">${i+1}. ${esc(p.name)}</button>`).join('');$('#map-list').querySelectorAll('button').forEach(b=>b.onclick=()=>focusMap(b.dataset.focus));if(!map)return;layer.clearLayers();markers={};ps.forEach((p,i)=>{const type=p.category==='金融'?'finance':p.category==='治理'?'governance':'';const icon=L.divIcon({className:'map-pin '+type,html:String(i+1),iconSize:[30,30],iconAnchor:[15,15]});const m=L.marker(p.coordinates,{icon,title:p.name,alt:p.name}).addTo(layer);const box=document.createElement('div');box.innerHTML=`<strong>${esc(p.name)}</strong><br>${esc(p.address)}<br><a target="_blank" rel="noopener" href="${navUrl(p)}">外部地图导航</a><br><button>阅读地点详情</button>`;box.querySelector('button').onclick=()=>openDetail(p.id);m.bindPopup(box);markers[p.id]=m});if(ps.length)map.fitBounds(L.latLngBounds(ps.map(p=>p.coordinates)).pad(.3),{maxZoom:16});}
function focusMap(id){const p=place(id);if(!p?.coordinates){toast('该地点尚未核实，暂不提供定位');return}if(!markers[id]){showAllMap=true;renderMap()}$('#map-section').scrollIntoView({behavior:'smooth'});if(map){map.setView(p.coordinates,16);markers[id]?.openPopup()}}
function openDetail(id,hash=true){const p=place(id);if(!p)return;$('#detail-body').innerHTML=`${p.image?`<img class="detail-photo" src="${p.image}" alt="${esc(p.photo.caption)}">`:''}<div class="detail-content"><p class="eyebrow">${esc(p.category)} / FIELD VISIT</p><h2>${esc(p.name)}</h2><p class="english">${esc(p.en)}</p><p class="visit">${esc(visit(p))}</p><p><strong>地址</strong> ${esc(p.address)}</p><p>${esc(p.intro)}</p><h3>${esc(p.topic)}</h3><ul>${p.questions.map(q=>'<li>'+esc(q)+'</li>').join('')}</ul><h3>入口与访问提醒</h3><p>${esc(p.entry)}</p>${p.coordinates?`<p class="credit">${esc(p.coordinateNote)}</p><a class="button" href="${navUrl(p)}" target="_blank" rel="noopener">外部地图导航</a><button class="button secondary" id="detail-map">在路书地图中查看</button>`:'<p>地址未核实，暂不提供地图标记和场地照片。</p>'}<button class="button secondary" id="share-place">复制地点链接</button>${p.photo?`<p class="credit">${esc(p.photo.caption)}<br>照片：${esc(p.photo.author)} / <a href="${p.photo.source}" target="_blank" rel="noopener">Wikimedia Commons</a> / <a href="${p.photo.licenseUrl}" target="_blank" rel="noopener">${esc(p.photo.license)}</a>。尺寸缩放与显示裁切；照片不是本次活动现场。</p>`:''}<p class="credit">资料：${p.sources.filter(s=>s!=='schedule').map(s=>{const src=data.sources.find(x=>x.id===s);return `<a href="${src.url}" target="_blank" rel="noopener">${esc(src.title)}</a>`}).join('；')}。时间依据V4正式行程。</p></div>`;if(!$('#detail').open)$('#detail').showModal();document.body.classList.add('modal-open');$('#detail-map')?.addEventListener('click',()=>{closeDetail();focusMap(id)});$('#share-place').onclick=async()=>{const url=location.href.split('#')[0]+'#place='+id;try{await navigator.clipboard.writeText(url);toast('地点链接已复制')}catch{toast('可从地址栏复制当前地点链接')}};if(hash)history.replaceState(null,'','#place='+id)}
function closeDetail(){if($('#detail').open)$('#detail').close();document.body.classList.remove('modal-open');history.replaceState(null,'','#day='+selected)}
async function start(){try{data=await(await fetch('data.json')).json();const hash=new URLSearchParams(location.hash.slice(1));const initial=hash.get('day');if(data.days.some(d=>d.date===initial))selected=initial;else{const now=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong'}).format(new Date());if(data.days.some(d=>d.date===now))selected=now}initMap();renderDay();renderCards();renderMap();$('#issues').innerHTML=data.issues.map(i=>'<li>'+esc(i)+'</li>').join('');$('#sources').innerHTML=data.sources.filter(s=>s.url).map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${esc(s.title)}</a>`).join('')+`<p>封面照片：${esc(data.heroPhoto.author)} / <a href="${data.heroPhoto.source_page_url}">Wikimedia Commons</a> / <a href="${data.heroPhoto.license_url}">${esc(data.heroPhoto.license)}</a>，显示裁切。</p>`;$('#place-filter').onchange=renderCards;$('#all-map').onclick=()=>{showAllMap=true;renderMap()};$('#today').onclick=()=>{const t=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong'}).format(new Date());if(data.days.some(d=>d.date===t))selectDate(t);else{selectDate('2026-10-11');toast('今天不在访学日期内，已显示10月11日')}};$('.close').onclick=closeDetail;$('#detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail()});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))closeDetail()});if(hash.has('place'))openDetail(hash.get('place'),false)}catch(e){$('#day-header').innerHTML='<p>行程暂时未能载入，请刷新页面，或下载PDF路书。</p>';console.error(e)}}
start();
window.addEventListener('hashchange',()=>{if(!data)return;const h=new URLSearchParams(location.hash.slice(1));if(h.has('place'))openDetail(h.get('place'),false);if(data.days.some(d=>d.date===h.get('day')))selectDate(h.get('day'),false)});
