'use strict';
(()=>{
 const status=document.querySelector('#offline-status'),panel=document.querySelector('.offline-panel'),retry=document.querySelector('#retry-offline'),update=document.querySelector('#update-app'),install=document.querySelector('#install-app');
 let registration,promptEvent,ready=false,reloading=false;
 const setStatus=(text,state)=>{status.textContent=text;panel.dataset.state=state};
 const readyText=()=>navigator.onLine?'已保存，可离线查阅（2026年10月9日版）。':'当前离线：行程、照片及参考地图均可查阅。';
 function callWorker(worker,type){return new Promise((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>reject(new Error('保存状态读取超时')),12000);channel.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data)};worker.postMessage({type},[channel.port2])})}
 async function checkReady(){const worker=navigator.serviceWorker.controller||registration?.active;if(!worker)return;try{const result=await callWorker(worker,'OFFLINE_STATUS');ready=result.ready;if(ready){retry.hidden=true;setStatus(readyText(),'ready')}else{setStatus('尚未完整保存，请联网后重新保存。','error');retry.hidden=false}}catch{setStatus('未能确认保存状态，请联网后重新保存。','error');retry.hidden=false}}
 function showUpdate(){if(registration?.waiting){update.hidden=false;update.disabled=false;update.textContent='更新路书';setStatus('新版路书已保存，请点击“更新路书”。','update')}}
 async function register(){retry.hidden=true;setStatus('正在保存行程、照片及参考地图，请保持联网……','saving');try{registration=await navigator.serviceWorker.register('sw.js',{scope:'./',updateViaCache:'none'});const observe=worker=>{if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'){if(navigator.serviceWorker.controller)showUpdate();else checkReady()}if(worker.state==='redundant'&&!ready){setStatus('保存未完成，请联网后重新保存。','error');retry.hidden=false}})};registration.addEventListener('updatefound',()=>observe(registration.installing));observe(registration.installing);if(registration.active)await checkReady();if(registration.waiting)showUpdate();else if(!registration.active){await navigator.serviceWorker.ready;await checkReady()}}catch{setStatus('保存未完成，请检查网络后重新保存。','error');retry.hidden=false}}
 if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading){location.reload();return}checkReady()});navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='CACHE_PROGRESS'&&!ready)setStatus(`正在保存离线内容（${e.data.done}/${e.data.total}），请保持联网……`,'saving');if(e.data?.type==='CACHE_FAILED'){setStatus('保存未完成，请检查网络后重新保存。','error');retry.hidden=false}});retry.onclick=()=>{if(!navigator.onLine){setStatus('请先联网，再点击“重新保存”。','error');return}register()};update.onclick=()=>{if(registration?.waiting){reloading=true;update.disabled=true;update.textContent='正在更新……';registration.waiting.postMessage({type:'SKIP_WAITING'})}};window.addEventListener('online',()=>{if(ready){setStatus(readyText(),'ready');registration?.update().catch(()=>{})}else register();showUpdate()});window.addEventListener('offline',()=>{if(ready){setStatus(readyText(),'ready');showUpdate()}else setStatus('离线内容尚未保存完成，请联网后重新保存。','error')});register()}else{setStatus('当前打开方式不支持离线保存。请在 Safari 或 Chrome 中打开本站，或下载 PDF。','unsupported')}
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;install.textContent='安装到主屏幕'});
 window.addEventListener('appinstalled',()=>{promptEvent=null;install.hidden=true});
 if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone)install.hidden=true;
 install.onclick=async()=>{if(promptEvent){await promptEvent.prompt();const result=await promptEvent.userChoice;if(result.outcome==='accepted')install.hidden=true;promptEvent=null;return}const ua=navigator.userAgent;const apple=/iPhone|iPad|iPod/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);document.querySelector('#install-instructions').textContent=apple?'请在 Safari 中打开本站，点击“分享”，选择“添加到主屏幕”，再点击“添加”。如在微信内打开，请先通过菜单选择在浏览器中打开。':'请在 Chrome 等支持安装的浏览器中打开本站，从浏览器菜单选择“安装应用”或“添加到主屏幕”。如在微信内打开，请先选择在浏览器中打开。';document.querySelector('#install-help').showModal()};
 document.querySelector('#close-install').onclick=()=>document.querySelector('#install-help').close();
})();
