'use strict';
const VERSION="20261009-59532b5aab27fc";
const ASSETS=["app.js","assets/icons/apple-touch-icon.png","assets/icons/icon-192.png","assets/icons/icon-512.png","assets/icons/icon-maskable.png","assets/images/airport.jpg","assets/images/ccxgfi.jpg","assets/images/cyberport.jpg","assets/images/dymon.jpg","assets/images/hero.jpg","assets/images/hku.jpg","assets/images/hotel.jpg","assets/images/investhk.jpg","assets/images/legco.jpg","assets/images/pku-logo.png","assets/images/science-park-lake.jpg","assets/images/science-park-overview.jpg","assets/images/science-park.jpg","assets/images/talent-office.jpg","assets/maps/day-11.png","assets/maps/day-12.png","assets/maps/day-13.png","assets/maps/day-14.png","assets/maps/day-15.png","assets/maps/day-16.png","assets/maps/day-17.png","assets/maps/overview.png","data.json","downloads/燕园翱翔香港实践团路书2026.docx","downloads/燕园翱翔香港实践团路书2026.pdf","index.html","manifest.webmanifest","pwa.js","sources.json","style.css","vendor/Leaflet-LICENSE","vendor/leaflet.css","vendor/leaflet.js"];
const PREFIX='yanyuan-hk-'+new URL(self.registration.scope).pathname.replace(/[^a-z0-9]/gi,'-')+'-';
const CACHE=PREFIX+VERSION;
const assetURLs=ASSETS.map(path=>new URL(path,self.registration.scope).href);
async function broadcast(data){const clients=await self.clients.matchAll({includeUncontrolled:true,type:'window'});for(const client of clients)client.postMessage(data)}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);let done=0;try{let index=0;async function fill(){while(index<assetURLs.length){const url=assetURLs[index++];const response=await fetch(new Request(url,{cache:'reload',credentials:'same-origin'}));if(!response.ok||response.type==='opaque')throw new Error('Unable to save '+url);await cache.put(url,response);done++;await broadcast({type:'CACHE_PROGRESS',done,total:assetURLs.length})}}const results=await Promise.allSettled(Array.from({length:4},fill));const failure=results.find(r=>r.status==='rejected');if(failure)throw failure.reason;if(!self.registration.active)await self.skipWaiting()}catch(error){await caches.delete(CACHE);await broadcast({type:'CACHE_FAILED'});throw error}})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith(PREFIX)&&key!==CACHE)await caches.delete(key);await self.clients.claim()})()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING'){self.skipWaiting();return}if(event.data?.type==='OFFLINE_STATUS'){event.waitUntil((async()=>{const cache=await caches.open(CACHE);const keys=new Set((await cache.keys()).map(r=>r.url));const complete=assetURLs.every(url=>keys.has(url));event.ports[0]?.postMessage({ready:complete,version:VERSION,count:keys.size,total:assetURLs.length})})())}});
async function rangeResponse(request,response){const range=request.headers.get('range');if(!range)return response;const match=/^bytes=(\d*)-(\d*)$/.exec(range);if(!match)return response;const buffer=await response.arrayBuffer(),length=buffer.byteLength;let start=match[1]?Number(match[1]):Math.max(0,length-Number(match[2])),end=match[1]?(match[2]?Number(match[2]):length-1):length-1;if(start>=length||end<start)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${length}`}});end=Math.min(end,length-1);const headers=new Headers(response.headers);headers.set('Content-Range',`bytes ${start}-${end}/${length}`);headers.set('Content-Length',String(end-start+1));headers.set('Accept-Ranges','bytes');return new Response(buffer.slice(start,end+1),{status:206,headers})}
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url),scope=new URL(self.registration.scope);if(request.method!=='GET'||url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);let response=await cache.match(request,{ignoreSearch:true});if(!response&&request.mode==='navigate'&&(url.pathname===scope.pathname||url.pathname===scope.pathname+'index.html'))response=await cache.match(new URL('index.html',scope).href);if(response)return rangeResponse(request,response);return fetch(request)})())});
